AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics:
  Enabled: false
