AllCops:
  TargetRubyVersion: 3.0

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/omniauth-liblynx.rb'

Metrics:
  Enabled: false
