AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Encoding:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics:
  Enabled: false
