rvm:
  - 2.6
before_install:
  - gem install bundler
install:
  - bundle install
deploy:
  provider: rubygems
  api_key:
    secure: gSm3W8gnVO4yIaCmZwid9EpvH6Vgex4xof+oqyAwi3rhtR1zNpnPoy2A0fjdkNcue2J3XRVXZoIO98MbqfvxLnTHOOFCutsod8X6jwj5xOp7xcTgiN8YvtH1RA+PwLdpfeoNlZcNjqcQL7RF7IAMQS0RVY3Tg2ioxSAG34TtnJDT7Ci+eSA4iFONhC3EsG8tFh3Ly4Y3dBuuFL3BQiZYYbPUX3gsyVOheBqZ2TcK1+EQyM7bct8hublJ3gb1FLgl15BdKZs/N5uEVkHxWS7rGDV+uqFoqr1uS5fUmp1F4e0P7QXcQTQ51ir6PkONGgwofxWNlMV9JnDD+f3san7hLBMjf1tqDb4fXeZEgRqi7M5FSfvwKaKzFDJ7VZcePUPsKt+xQNS/SA562xxuOPqzrMCEja5N1dINBoypcXZoYVEzkU0ojwHhaIPm89hbx4cH0Ky5vL2fxQzNLQQRw1TjXDy/pxP1h034/T9wKXwzg9R8aY6m3EnFiOrmc7yKHdG4wuWhhtH6eBSb8567TdtF1ArsrFd/Lk3Di7FMDLS7zITwgT6RyKPUvyabC/u98KdMfF0GcZ8ri3UK+XeTHdFU3d7cky4354h4uxwZpyes4r7vHN0Z4DnXqvR/g/OGRqo4TsNoxxCIQ5fM+DJPVTtqgqVOwGKsPfkELYdHLMwgbAo=
  gem: omniauth-liblynx
  on:
    tags: true
    repo: dsablic/omniauth-liblynx
