rvm:
  - 2.6
before_install:
  - gem install bundler
install:
  - bundle install
deploy:
  provider: rubygems
  api_key:
    secure: "wuLcn5cvlHkqi1SoZKYXJNGfnL/QYECC6cZ5Z/Y5SosgeO7XAfa259yNadyl/Wo9cQrN/aS7OZWaIrjvuclXRxc1OEYkSAcuBUpIRfO68nzwhi0X0s1+W81hcOcpKP2GZn3l9JrpvVdkU4Dq5D8gWKf9EFpJCJd5RZ+KnwrHp77AA5/EZ14PVxKlszxa5oOVIOA2+TuJbtbDC1zHFCK7d1rrj/06boMgkZVSOHocwdpWcC4GZymLAlNQmhbFIGerMk2LkPS3DjQIzORRZ8aTIHLE26mMj+vWivaCwJ0UCqgU2/i0ADwQ22ca/ScMJ+EUv3s73FRKoYUGnNZ6ME6BXnVC8gQok2vjnezh2/fVvWIO7c1alDpKrDkVh75N1snyer3QYS/mQzdYzYl+4eLvLS4D4X4lBayKDlZSBUIHbQVsM750aprKchw++DwKqs82SSH4aT6FX5boZBiysiPorM+BjKGqdc2QgJ4Pf32UFXoTbFbiIfIw3xUO9fdM2qoo69atewZlpTvBqHoHl/QSOrKm3YitG50kv/J6su/29ctlZldX685d/HLMgYhTOQ6xssYy41lwDMAKnMKQ3vhTPmv2r64axgUJC7vczxCTtQKa/1l2K0ZzNO3jiTFOps1xE8UMvsV/Dke0OElSqKr5E2/kLhHxrouM6VaELUZFZ74="
  gem: omniauth-liblynx
  on:
    tags: true
    repo: dsablic/omniauth-liblynx
